#!/usr/bin/env python3
"""
品牌追踪配置表 v3 — 15个品牌，关键词按收入驱动因素定制
"""

BRANDS = [
    {
        "name": "泡泡玛特",
        "code": "9992",
        "market": "港股",
        "google_keyword": "Pop Mart",
        "domestic_keywords": ["泡泡玛特", "popmart", "LABUBU", "labubu", "dimoo", "skullpanda"],
        "industry": "潮玩",
    },
    {
        "name": "蜜雪集团",
        "code": "2097",
        "market": "港股",
        "google_keyword": "Mixue",
        "domestic_keywords": ["蜜雪冰城", "蜜雪", "Mixue", "雪王"],
        "industry": "餐饮饮品",
    },
    {
        "name": "小米集团",
        "code": "1810",
        "market": "港股",
        "google_keyword": "Xiaomi",
        "domestic_keywords": ["小米", "红米", "REDMI", "SU7", "澎湃OS", "小米汽车"],
        "industry": "消费电子",
    },
    {
        "name": "东方甄选",
        "code": "1797",
        "market": "港股",
        "google_keyword": "东方甄选",
        "domestic_keywords": ["东方甄选", "东方甄选自营"],
        "industry": "直播电商",
    },
    {
        "name": "阿里巴巴",
        "code": "9988",
        "market": "港股",
        "google_keyword": "Taobao",
        "domestic_keywords": ["淘宝", "天猫", "支付宝", "88VIP", "阿里"],
        "industry": "互联网",
    },
    {
        "name": "腾讯控股",
        "code": "0700",
        "market": "港股",
        "google_keyword": "WeChat",
        "domestic_keywords": ["微信", "王者荣耀", "视频号", "腾讯"],
        "industry": "互联网",
    },
    {
        "name": "小鹏汽车",
        "code": "9868",
        "market": "港股",
        "google_keyword": "XPeng",
        "domestic_keywords": ["小鹏", "XPeng", "MONA", "G6", "P7"],
        "industry": "新能源车",
    },
    {
        "name": "美团",
        "code": "3690",
        "market": "港股",
        "google_keyword": "Meituan",
        "domestic_keywords": ["美团", "美团外卖", "美团优选", "美团买菜"],
        "industry": "本地生活",
    },
    {
        "name": "携程",
        "code": "9961",
        "market": "港股",
        "google_keyword": "Ctrip",
        "domestic_keywords": ["携程", "携程旅行", "去哪儿"],
        "industry": "在线旅游",
    },
    {
        "name": "老铺黄金",
        "code": "6181",
        "market": "港股",
        "google_keyword": "老铺黄金",
        "domestic_keywords": ["老铺黄金", "老铺"],
        "industry": "黄金珠宝",
    },
    {
        "name": "中芯国际",
        "code": "0981",
        "market": "港股",
        "google_keyword": "SMIC",
        "domestic_keywords": ["中芯国际", "中芯", "晶圆代工"],
        "industry": "半导体",
    },
    {
        "name": "农夫山泉",
        "code": "9633",
        "market": "港股",
        "google_keyword": "农夫山泉",
        "domestic_keywords": ["农夫山泉", "农夫", "东方树叶", "茶π"],
        "industry": "饮品",
    },
    {
        "name": "华虹宏力",
        "code": "1347",
        "market": "港股",
        "google_keyword": "Hua Hong",
        "domestic_keywords": ["华虹", "华虹宏力"],
        "industry": "半导体",
    },
    {
        "name": "宁德时代",
        "code": "300750",
        "market": "A股",
        "google_keyword": "electric vehicle",
        "domestic_keywords": ["宁德时代", "CATL", "宁德", "新能源车", "电车"],
        "industry": "电池",
    },
    {
        "name": "智谱",
        "code": "—",
        "market": "未上市",
        "google_keyword": "ChatGLM",
        "domestic_keywords": ["智谱", "智谱AI", "ChatGLM"],
        "industry": "AI",
    },
]
